CREATE TABLE IF NOT EXISTS  USER (
   ID                         BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
   FIRST_NAME                 VARCHAR(50)  NOT NULL,
   LAST_NAME                  VARCHAR(50)  NOT NULL,
   PASSPORT_SERIAL            VARCHAR(50),
   PASSPORT_NUMBER            VARCHAR(50),
   PASSPORT_DATE_OF_ISSUE     VARCHAR(50),
   CLIENT_TYPE                VARCHAR(10)  NOT NULL DEFAULT 'NEW'
);

CREATE TABLE IF NOT EXISTS COUNTRY (
   ID           BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
   NAME         VARCHAR(50) NOT NULL,
   LANGUAGE     VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CITY (
   ID                    BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
   COUNTRY_ID            BIGINT      NOT NULL,
   NAME                  VARCHAR(50) NOT NULL,
   POPULATION 		 INT         NOT NULL,
   IS_CAPITAL            BOOLEAN,    NOT NULL,
   CLIMATE		 VARCHAR(50) NOT NULL,
   NAME                  VARCHAR(50) NOT NULL,
   DISCRIMINATOR         VARCHAR(50) NOT NULL,
   NUM_OF_BEACHES        VARCHAR(50)
   NUM_OF_SIGHTS         VARCHAR(50)
   NUM_OF_SKI_RESORTS    VARCHAR(50)

   FOREIGN KEY (COUNTRY_ID) references COUNTRY (ID)
);

CREATE TABLE IF NOT EXISTS ORDR (
  ID                    BIGINT      NOT NULL AUTO_INCREMENT PRIMARY KEY,
  COUNTRY_ID            BIGINT      NOT NULL,
  CITY_ID               BIGINT      NOT NULL,
  USER_ID               BIGINT      NOT NULL,
  PRICE                 INT,
  DESCRIPTION           VARCHAR(150),

 FOREIGN KEY (USER_ID) references USER (ID),
 FOREIGN KEY (COUNTRY_ID) references COUNTRY (ID),
 FOREIGN KEY (CITY_ID) references CITY (ID)
);